kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.1626117420544295
    roll: -0
    pitch: 0
    yaw: 3.872457239248451e-08
  upper_arm:
    x: 3.125830761359127e-05
    y: 0
    z: 0
    roll: 1.570341205700431
    pitch: 0
    yaw: 2.813928341110484e-06
  forearm:
    x: -0.4252175635239808
    y: 0
    z: 0
    roll: 3.141464652493966
    pitch: 3.141067746882002
    yaw: -3.141592265591304
  wrist_1:
    x: -0.3922972098016012
    y: 2.528085864383388e-05
    z: 0.1337103732761116
    roll: 3.141403581809323
    pitch: 3.140361599743703
    yaw: -3.141590342034739
  wrist_2:
    x: 6.570406933913473e-05
    y: -0.09975243963571551
    z: 0.0001135522370311698
    roll: 1.569657986836514
    pitch: 0
    yaw: 2.589011072265391e-07
  wrist_3:
    x: 8.856111047191416e-05
    y: 0.09969305881449084
    z: 6.457102091203178e-05
    roll: 1.571444024966168
    pitch: 3.141592653589793
    yaw: -3.141592544972426
  hash: calib_347409456257688176
