kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.1627091939762065
    roll: -0
    pitch: 0
    yaw: 3.872490670492335e-08
  upper_arm:
    x: 0.0002176273920566163
    y: 0
    z: 0
    roll: 1.571626569802581
    pitch: 0
    yaw: -2.802107518022109e-06
  forearm:
    x: -0.4251930856778653
    y: 0
    z: 0
    roll: 3.140945666991923
    pitch: -3.140611403299111
    yaw: -3.141590247215072
  wrist_1:
    x: -0.3923810760273991
    y: -0.001106784298841813
    z: 0.1334541113124731
    roll: 0.008293179686530146
    pitch: 0.0004324375844974205
    yaw: -2.761802697809752e-06
  wrist_2:
    x: 4.693696392419047e-05
    y: -0.0996819300594925
    z: 0.0001755069560750966
    roll: 1.569035658892339
    pitch: 0
    yaw: -5.106825391625653e-07
  wrist_3:
    x: 5.806411932982701e-06
    y: 0.09965721622929842
    z: 0.0001233405409320115
    roll: 1.572033974028306
    pitch: 3.141592653589793
    yaw: -3.141592362895824
  hash: calib_3762659842242873398